version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - infra/postgres/.env
#    volumes:
#      - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U auth_user -d auth_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
#    volumes:
#      - redis-data:/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  auth-api:
    build:
      context: .
      target: development
    env_file:
      - .env.docker
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

#volumes:
#  postgres-data:
#  redis-data:
